### ISSUE TITLE
The .Net SDK 6.0.302 fail compiling MvvmGen projects using WPF

### ISSUE THREAD

**Issue by Dragnalith** [thomasclaudiushuber/mvvmgen#43]
### Describe the bug
The .Net SDK 6.0.302 fail compiling MvvmGen projects using WPF. (Projects which compile correctly if you use .Net SDK 6.0.300)

I have open [a bug report on the SDK side](https://github.com/dotnet/sdk/issues/26581) too because I am not sure if it is a MvvmGen issue or SDK issue.

### To Reproduce
This [ConsoleApp8.zip](https://github.com/thomasclaudiushuber/mvvmgen/files/9111863/ConsoleApp8.zip) can reproduce the issue

- Install .Net SDK 6.0.300 (you need to uninstall .Net SDK 6.0.302 to install the 6.0.300)
- Install .Net SDK 6.0.302
- Check both SDK are installed using `dotnet --list-sdks`
- Unzip ConsoleApp8.zip (attached to this issue)
- Run `dotnet build ConsoleApp8.sln`
- _Notice compilation fail_
- Modify the global.json file and change the value from `6.0.302` to `6.0.300`
- Run `dotnet build ConsoleApp8.sln`
- _Notice the compilation is successful_

### Further technical details
- I can also reproduce the problem by executing the build through Visual Studio 2022 GUI
- The problem disappear if you remove the `xmlns:local="clr-namespace:MyNamespace"` on MyApp.xaml
- The compilation error looks like:
```
ConsoleApp8\MvvmGen.SourceGenerators\MvvmGen.ViewModelGenerator\MyNamespace.MyViewModel.g.cs(19,22,19,34): error CS0756: A partial method may not have multiple defining declarations
ConsoleApp8\MvvmGen.SourceGenerators\MvvmGen.ViewModelGenerator\MyNamespace.MyViewModel.g.cs(14,16,14,27): error CS0111: Type 'MyViewModel' already defines a member called 'MyViewModel' with the same parameter types
ConsoleApp8\MvvmGen.SourceGenerators\MvvmGen.ViewModelGenerator\MyNamespace.MyViewModel.g.cs(19,22,19,34): error CS0111: Type 'MyViewModel' already defines a member called 'OnInitialize' with the same parameter types
```

**Comment by Dugnom** [comment]
Just to shorten your path, it seems to be a WPF issue.
You can see the progress on resolving the issue (and temporary workarounds) here: https://github.com/dotnet/wpf/issues/6792

**Comment by thomasclaudiushuber** [comment]
Thank you @Dragnalith and @Dugnom for your comments and for pointing to the WPF issue for this one. Hope it will be fixed soon, then I'll close this issue.

**Comment by Dragnalith** [comment]
@thomasclaudiushuber
.Net Core people told the bug has been fixed and it will be part of the next SDK release.

**Comment by mcgresearch** [comment]
See here [https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md](url) for a fix

**Comment by Dugnom** [comment]
@mcgresearch your link is broken, I think you meant to link to https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608 . I add the text of the current md at time of writing for future reference at the end. Correct me if this is not the content you wanted to link to, I may have misunderstood your intention. 


### Issues building WPF application with Windows Desktop 6.0.7 and 6.0.8

Some customers are unable to build WPF applications with Windows Desktop 6.0.7 and 6.0.8, if they are including source generators coming from NuGet Packages, and receive errors similar to :
```
Rebuild started...
1>------ Rebuild All started: Project: ObservablePropertyTest, Configuration: Debug Any CPU ------
Restored C:\git\ObservablePropertyTest\ObservablePropertyTest.csproj (in 2 ms).
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\__KnownINotifyPropertyChangedOrChangingArgs.cs(12,27,12,70): error CS0101: The namespace 'CommunityToolkit.Mvvm.ComponentModel.__Internals' already contains a definition for '__KnownINotifyPropertyChangedOrChangingArgs'
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\__KnownINotifyPropertyChangedOrChangingArgs.cs(7,6,7,51): error CS0579: Duplicate 'global::System.CodeDom.Compiler.GeneratedCode' attribute
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\__KnownINotifyPropertyChangedOrChangingArgs.cs(8,6,8,52): error CS0579: Duplicate 'global::System.Diagnostics.DebuggerNonUserCode' attribute
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\__KnownINotifyPropertyChangedOrChangingArgs.cs(9,6,9,69): error CS0579: Duplicate 'global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage' attribute
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\__KnownINotifyPropertyChangedOrChangingArgs.cs(10,6,10,51): error CS0579: Duplicate 'global::System.ComponentModel.EditorBrowsable' attribute
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\__KnownINotifyPropertyChangedOrChangingArgs.cs(11,6,11,29): error CS0579: Duplicate 'global::System.Obsolete' attribute
1>C:\git\ObservablePropertyTest\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\ObservablePropertyTest.TestVM.cs(12,23,12,33): error CS0102: The type 'TestVM' already contains a definition for 'TestString'
1>Done building project "ObservablePropertyTest_yynlzhol_wpftmp.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

This happened because WPF builds in 6.0.7 onwards, only considered source generators that were coming from nuget references. This caused an issue when there were source generators that were essentially coming via FrameworkReference. This issue has already been addressed in next release (6.0.9). However, the following workaround would unblock WPF builds.

**Fix:**
* To enable build in Windows Desktop 6.0.7, navigate to the directory containing the `Microsoft.WinFx.targets` file ( `C:\Program Files\dotnet\sdk\6.0.302\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets` )
* Add the following target in the file : 
    ```xml

    <Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
        <ItemGroup>
            <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
            <Analyzer Remove="@(Analyzer)" />
            <Analyzer Include="@(FilteredAnalyzer)" />
        </ItemGroup>
    </Target>    
    ```

**Comment by thomasclaudiushuber** [comment]
Closing this, as this seems to be fixed with more recent .NET SDKs.
